on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.3'
      - run: |
          cd firstProgram/wc
          go test -v
          go build
      - run: |
          cd interacting/todo
          go test -v
          go build
